FROM alpine:3.16.0

RUN apk add --update --no-cache \
    bash \
    wget && \
    rm -rf /var/cache/apk/*

RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/81b1373f17855a4dc21156cfe1694c31d7d1792e/wait-for-it.sh

RUN chmod +x wait-for-it.sh

ENTRYPOINT [ "/bin/bash", "-c" ]
