/* eslint-disable */
// @generated by protoc-gen-es v0.0.1 with parameter "bootstrap_wkt=true,ts_nocheck=false"
// @generated from file google/protobuf/descriptor.proto (package google.protobuf, syntax proto2)

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "../../index.js";
import {Message, proto2} from "../../index.js";

/**
 * @generated from message google.protobuf.FileDescriptorSet
 */
export class FileDescriptorSet extends Message<FileDescriptorSet> {

    /**
     * @generated from field: repeated google.protobuf.FileDescriptorProto file = 1;
     */
    file: FileDescriptorProto[] = [];

    constructor(data?: PartialMessage<FileDescriptorSet>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.FileDescriptorSet";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "file", kind: "message", T: FileDescriptorProto, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FileDescriptorSet {
        return new FileDescriptorSet().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FileDescriptorSet {
        return new FileDescriptorSet().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FileDescriptorSet {
        return new FileDescriptorSet().fromJsonString(jsonString, options);
    }

    static equals(a: FileDescriptorSet | PlainMessage<FileDescriptorSet> | undefined, b: FileDescriptorSet | PlainMessage<FileDescriptorSet> | undefined): boolean {
        return proto2.util.equals(FileDescriptorSet, a, b);
    }

}


/**
 * @generated from message google.protobuf.FileDescriptorProto
 */
export class FileDescriptorProto extends Message<FileDescriptorProto> {

    /**
     * @generated from field: optional string name = 1;
     */
    name?: string;

    /**
     * @generated from field: optional string package = 2;
     */
    package?: string;

    /**
     * @generated from field: repeated string dependency = 3;
     */
    dependency: string[] = [];

    /**
     * @generated from field: repeated int32 public_dependency = 10;
     */
    publicDependency: number[] = [];

    /**
     * @generated from field: repeated int32 weak_dependency = 11;
     */
    weakDependency: number[] = [];

    /**
     * @generated from field: repeated google.protobuf.DescriptorProto message_type = 4;
     */
    messageType: DescriptorProto[] = [];

    /**
     * @generated from field: repeated google.protobuf.EnumDescriptorProto enum_type = 5;
     */
    enumType: EnumDescriptorProto[] = [];

    /**
     * @generated from field: repeated google.protobuf.ServiceDescriptorProto service = 6;
     */
    service: ServiceDescriptorProto[] = [];

    /**
     * @generated from field: repeated google.protobuf.FieldDescriptorProto extension = 7;
     */
    extension: FieldDescriptorProto[] = [];

    /**
     * @generated from field: optional google.protobuf.FileOptions options = 8;
     */
    options?: FileOptions;

    /**
     * @generated from field: optional google.protobuf.SourceCodeInfo source_code_info = 9;
     */
    sourceCodeInfo?: SourceCodeInfo;

    /**
     * @generated from field: optional string syntax = 12;
     */
    syntax?: string;

    constructor(data?: PartialMessage<FileDescriptorProto>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.FileDescriptorProto";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 2, name: "package", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 3, name: "dependency", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true},
        {no: 10, name: "public_dependency", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true},
        {no: 11, name: "weak_dependency", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true},
        {no: 4, name: "message_type", kind: "message", T: DescriptorProto, repeated: true},
        {no: 5, name: "enum_type", kind: "message", T: EnumDescriptorProto, repeated: true},
        {no: 6, name: "service", kind: "message", T: ServiceDescriptorProto, repeated: true},
        {no: 7, name: "extension", kind: "message", T: FieldDescriptorProto, repeated: true},
        {no: 8, name: "options", kind: "message", T: FileOptions, opt: true},
        {no: 9, name: "source_code_info", kind: "message", T: SourceCodeInfo, opt: true},
        {no: 12, name: "syntax", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FileDescriptorProto {
        return new FileDescriptorProto().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FileDescriptorProto {
        return new FileDescriptorProto().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FileDescriptorProto {
        return new FileDescriptorProto().fromJsonString(jsonString, options);
    }

    static equals(a: FileDescriptorProto | PlainMessage<FileDescriptorProto> | undefined, b: FileDescriptorProto | PlainMessage<FileDescriptorProto> | undefined): boolean {
        return proto2.util.equals(FileDescriptorProto, a, b);
    }

}


/**
 * @generated from message google.protobuf.DescriptorProto
 */
export class DescriptorProto extends Message<DescriptorProto> {

    /**
     * @generated from field: optional string name = 1;
     */
    name?: string;

    /**
     * @generated from field: repeated google.protobuf.FieldDescriptorProto field = 2;
     */
    field: FieldDescriptorProto[] = [];

    /**
     * @generated from field: repeated google.protobuf.FieldDescriptorProto extension = 6;
     */
    extension: FieldDescriptorProto[] = [];

    /**
     * @generated from field: repeated google.protobuf.DescriptorProto nested_type = 3;
     */
    nestedType: DescriptorProto[] = [];

    /**
     * @generated from field: repeated google.protobuf.EnumDescriptorProto enum_type = 4;
     */
    enumType: EnumDescriptorProto[] = [];

    /**
     * @generated from field: repeated google.protobuf.DescriptorProto.ExtensionRange extension_range = 5;
     */
    extensionRange: DescriptorProto_ExtensionRange[] = [];

    /**
     * @generated from field: repeated google.protobuf.OneofDescriptorProto oneof_decl = 8;
     */
    oneofDecl: OneofDescriptorProto[] = [];

    /**
     * @generated from field: optional google.protobuf.MessageOptions options = 7;
     */
    options?: MessageOptions;

    /**
     * @generated from field: repeated google.protobuf.DescriptorProto.ReservedRange reserved_range = 9;
     */
    reservedRange: DescriptorProto_ReservedRange[] = [];

    /**
     * @generated from field: repeated string reserved_name = 10;
     */
    reservedName: string[] = [];

    constructor(data?: PartialMessage<DescriptorProto>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.DescriptorProto";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 2, name: "field", kind: "message", T: FieldDescriptorProto, repeated: true},
        {no: 6, name: "extension", kind: "message", T: FieldDescriptorProto, repeated: true},
        {no: 3, name: "nested_type", kind: "message", T: DescriptorProto, repeated: true},
        {no: 4, name: "enum_type", kind: "message", T: EnumDescriptorProto, repeated: true},
        {no: 5, name: "extension_range", kind: "message", T: DescriptorProto_ExtensionRange, repeated: true},
        {no: 8, name: "oneof_decl", kind: "message", T: OneofDescriptorProto, repeated: true},
        {no: 7, name: "options", kind: "message", T: MessageOptions, opt: true},
        {no: 9, name: "reserved_range", kind: "message", T: DescriptorProto_ReservedRange, repeated: true},
        {no: 10, name: "reserved_name", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DescriptorProto {
        return new DescriptorProto().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DescriptorProto {
        return new DescriptorProto().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DescriptorProto {
        return new DescriptorProto().fromJsonString(jsonString, options);
    }

    static equals(a: DescriptorProto | PlainMessage<DescriptorProto> | undefined, b: DescriptorProto | PlainMessage<DescriptorProto> | undefined): boolean {
        return proto2.util.equals(DescriptorProto, a, b);
    }

}

/**
 * @generated from message google.protobuf.DescriptorProto.ExtensionRange
 */
export class DescriptorProto_ExtensionRange extends Message<DescriptorProto_ExtensionRange> {

    /**
     * @generated from field: optional int32 start = 1;
     */
    start?: number;

    /**
     * @generated from field: optional int32 end = 2;
     */
    end?: number;

    /**
     * @generated from field: optional google.protobuf.ExtensionRangeOptions options = 3;
     */
    options?: ExtensionRangeOptions;

    constructor(data?: PartialMessage<DescriptorProto_ExtensionRange>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.DescriptorProto.ExtensionRange";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "start", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
        {no: 2, name: "end", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
        {no: 3, name: "options", kind: "message", T: ExtensionRangeOptions, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DescriptorProto_ExtensionRange {
        return new DescriptorProto_ExtensionRange().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DescriptorProto_ExtensionRange {
        return new DescriptorProto_ExtensionRange().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DescriptorProto_ExtensionRange {
        return new DescriptorProto_ExtensionRange().fromJsonString(jsonString, options);
    }

    static equals(a: DescriptorProto_ExtensionRange | PlainMessage<DescriptorProto_ExtensionRange> | undefined, b: DescriptorProto_ExtensionRange | PlainMessage<DescriptorProto_ExtensionRange> | undefined): boolean {
        return proto2.util.equals(DescriptorProto_ExtensionRange, a, b);
    }

}


/**
 * @generated from message google.protobuf.DescriptorProto.ReservedRange
 */
export class DescriptorProto_ReservedRange extends Message<DescriptorProto_ReservedRange> {

    /**
     * @generated from field: optional int32 start = 1;
     */
    start?: number;

    /**
     * @generated from field: optional int32 end = 2;
     */
    end?: number;

    constructor(data?: PartialMessage<DescriptorProto_ReservedRange>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.DescriptorProto.ReservedRange";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "start", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
        {no: 2, name: "end", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DescriptorProto_ReservedRange {
        return new DescriptorProto_ReservedRange().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DescriptorProto_ReservedRange {
        return new DescriptorProto_ReservedRange().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DescriptorProto_ReservedRange {
        return new DescriptorProto_ReservedRange().fromJsonString(jsonString, options);
    }

    static equals(a: DescriptorProto_ReservedRange | PlainMessage<DescriptorProto_ReservedRange> | undefined, b: DescriptorProto_ReservedRange | PlainMessage<DescriptorProto_ReservedRange> | undefined): boolean {
        return proto2.util.equals(DescriptorProto_ReservedRange, a, b);
    }

}



/**
 * @generated from message google.protobuf.ExtensionRangeOptions
 */
export class ExtensionRangeOptions extends Message<ExtensionRangeOptions> {

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<ExtensionRangeOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.ExtensionRangeOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExtensionRangeOptions {
        return new ExtensionRangeOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExtensionRangeOptions {
        return new ExtensionRangeOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExtensionRangeOptions {
        return new ExtensionRangeOptions().fromJsonString(jsonString, options);
    }

    static equals(a: ExtensionRangeOptions | PlainMessage<ExtensionRangeOptions> | undefined, b: ExtensionRangeOptions | PlainMessage<ExtensionRangeOptions> | undefined): boolean {
        return proto2.util.equals(ExtensionRangeOptions, a, b);
    }

}


/**
 * @generated from message google.protobuf.FieldDescriptorProto
 */
export class FieldDescriptorProto extends Message<FieldDescriptorProto> {

    /**
     * @generated from field: optional string name = 1;
     */
    name?: string;

    /**
     * @generated from field: optional int32 number = 3;
     */
    number?: number;

    /**
     * @generated from field: optional google.protobuf.FieldDescriptorProto.Label label = 4;
     */
    label?: FieldDescriptorProto_Label;

    /**
     * @generated from field: optional google.protobuf.FieldDescriptorProto.Type type = 5;
     */
    type?: FieldDescriptorProto_Type;

    /**
     * @generated from field: optional string type_name = 6;
     */
    typeName?: string;

    /**
     * @generated from field: optional string extendee = 2;
     */
    extendee?: string;

    /**
     * @generated from field: optional string default_value = 7;
     */
    defaultValue?: string;

    /**
     * @generated from field: optional int32 oneof_index = 9;
     */
    oneofIndex?: number;

    /**
     * @generated from field: optional string json_name = 10;
     */
    jsonName?: string;

    /**
     * @generated from field: optional google.protobuf.FieldOptions options = 8;
     */
    options?: FieldOptions;

    /**
     * @generated from field: optional bool proto3_optional = 17;
     */
    proto3Optional?: boolean;

    constructor(data?: PartialMessage<FieldDescriptorProto>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.FieldDescriptorProto";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 3, name: "number", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
        {no: 4, name: "label", kind: "enum", T: proto2.getEnumType(FieldDescriptorProto_Label), opt: true},
        {no: 5, name: "type", kind: "enum", T: proto2.getEnumType(FieldDescriptorProto_Type), opt: true},
        {no: 6, name: "type_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 2, name: "extendee", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 7, name: "default_value", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 9, name: "oneof_index", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
        {no: 10, name: "json_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 8, name: "options", kind: "message", T: FieldOptions, opt: true},
        {no: 17, name: "proto3_optional", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FieldDescriptorProto {
        return new FieldDescriptorProto().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FieldDescriptorProto {
        return new FieldDescriptorProto().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FieldDescriptorProto {
        return new FieldDescriptorProto().fromJsonString(jsonString, options);
    }

    static equals(a: FieldDescriptorProto | PlainMessage<FieldDescriptorProto> | undefined, b: FieldDescriptorProto | PlainMessage<FieldDescriptorProto> | undefined): boolean {
        return proto2.util.equals(FieldDescriptorProto, a, b);
    }

}

/**
 * @generated from enum google.protobuf.FieldDescriptorProto.Type
 */
export enum FieldDescriptorProto_Type {

    /**
     * @generated from enum value: TYPE_DOUBLE = 1;
     */
    DOUBLE = 1,

    /**
     * @generated from enum value: TYPE_FLOAT = 2;
     */
    FLOAT = 2,

    /**
     * @generated from enum value: TYPE_INT64 = 3;
     */
    INT64 = 3,

    /**
     * @generated from enum value: TYPE_UINT64 = 4;
     */
    UINT64 = 4,

    /**
     * @generated from enum value: TYPE_INT32 = 5;
     */
    INT32 = 5,

    /**
     * @generated from enum value: TYPE_FIXED64 = 6;
     */
    FIXED64 = 6,

    /**
     * @generated from enum value: TYPE_FIXED32 = 7;
     */
    FIXED32 = 7,

    /**
     * @generated from enum value: TYPE_BOOL = 8;
     */
    BOOL = 8,

    /**
     * @generated from enum value: TYPE_STRING = 9;
     */
    STRING = 9,

    /**
     * @generated from enum value: TYPE_GROUP = 10;
     */
    GROUP = 10,

    /**
     * @generated from enum value: TYPE_MESSAGE = 11;
     */
    MESSAGE = 11,

    /**
     * @generated from enum value: TYPE_BYTES = 12;
     */
    BYTES = 12,

    /**
     * @generated from enum value: TYPE_UINT32 = 13;
     */
    UINT32 = 13,

    /**
     * @generated from enum value: TYPE_ENUM = 14;
     */
    ENUM = 14,

    /**
     * @generated from enum value: TYPE_SFIXED32 = 15;
     */
    SFIXED32 = 15,

    /**
     * @generated from enum value: TYPE_SFIXED64 = 16;
     */
    SFIXED64 = 16,

    /**
     * @generated from enum value: TYPE_SINT32 = 17;
     */
    SINT32 = 17,

    /**
     * @generated from enum value: TYPE_SINT64 = 18;
     */
    SINT64 = 18,

}

// Retrieve enum metadata with: proto2.getEnumType(FieldDescriptorProto_Type)
proto2.util.setEnumType(FieldDescriptorProto_Type, "google.protobuf.FieldDescriptorProto.Type", [
    {no: 1, name: "TYPE_DOUBLE"},
    {no: 2, name: "TYPE_FLOAT"},
    {no: 3, name: "TYPE_INT64"},
    {no: 4, name: "TYPE_UINT64"},
    {no: 5, name: "TYPE_INT32"},
    {no: 6, name: "TYPE_FIXED64"},
    {no: 7, name: "TYPE_FIXED32"},
    {no: 8, name: "TYPE_BOOL"},
    {no: 9, name: "TYPE_STRING"},
    {no: 10, name: "TYPE_GROUP"},
    {no: 11, name: "TYPE_MESSAGE"},
    {no: 12, name: "TYPE_BYTES"},
    {no: 13, name: "TYPE_UINT32"},
    {no: 14, name: "TYPE_ENUM"},
    {no: 15, name: "TYPE_SFIXED32"},
    {no: 16, name: "TYPE_SFIXED64"},
    {no: 17, name: "TYPE_SINT32"},
    {no: 18, name: "TYPE_SINT64"},
]);

/**
 * @generated from enum google.protobuf.FieldDescriptorProto.Label
 */
export enum FieldDescriptorProto_Label {

    /**
     * @generated from enum value: LABEL_OPTIONAL = 1;
     */
    OPTIONAL = 1,

    /**
     * @generated from enum value: LABEL_REQUIRED = 2;
     */
    REQUIRED = 2,

    /**
     * @generated from enum value: LABEL_REPEATED = 3;
     */
    REPEATED = 3,

}

// Retrieve enum metadata with: proto2.getEnumType(FieldDescriptorProto_Label)
proto2.util.setEnumType(FieldDescriptorProto_Label, "google.protobuf.FieldDescriptorProto.Label", [
    {no: 1, name: "LABEL_OPTIONAL"},
    {no: 2, name: "LABEL_REQUIRED"},
    {no: 3, name: "LABEL_REPEATED"},
]);


/**
 * @generated from message google.protobuf.OneofDescriptorProto
 */
export class OneofDescriptorProto extends Message<OneofDescriptorProto> {

    /**
     * @generated from field: optional string name = 1;
     */
    name?: string;

    /**
     * @generated from field: optional google.protobuf.OneofOptions options = 2;
     */
    options?: OneofOptions;

    constructor(data?: PartialMessage<OneofDescriptorProto>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.OneofDescriptorProto";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 2, name: "options", kind: "message", T: OneofOptions, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OneofDescriptorProto {
        return new OneofDescriptorProto().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OneofDescriptorProto {
        return new OneofDescriptorProto().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OneofDescriptorProto {
        return new OneofDescriptorProto().fromJsonString(jsonString, options);
    }

    static equals(a: OneofDescriptorProto | PlainMessage<OneofDescriptorProto> | undefined, b: OneofDescriptorProto | PlainMessage<OneofDescriptorProto> | undefined): boolean {
        return proto2.util.equals(OneofDescriptorProto, a, b);
    }

}


/**
 * @generated from message google.protobuf.EnumDescriptorProto
 */
export class EnumDescriptorProto extends Message<EnumDescriptorProto> {

    /**
     * @generated from field: optional string name = 1;
     */
    name?: string;

    /**
     * @generated from field: repeated google.protobuf.EnumValueDescriptorProto value = 2;
     */
    value: EnumValueDescriptorProto[] = [];

    /**
     * @generated from field: optional google.protobuf.EnumOptions options = 3;
     */
    options?: EnumOptions;

    /**
     * @generated from field: repeated google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4;
     */
    reservedRange: EnumDescriptorProto_EnumReservedRange[] = [];

    /**
     * @generated from field: repeated string reserved_name = 5;
     */
    reservedName: string[] = [];

    constructor(data?: PartialMessage<EnumDescriptorProto>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.EnumDescriptorProto";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 2, name: "value", kind: "message", T: EnumValueDescriptorProto, repeated: true},
        {no: 3, name: "options", kind: "message", T: EnumOptions, opt: true},
        {no: 4, name: "reserved_range", kind: "message", T: EnumDescriptorProto_EnumReservedRange, repeated: true},
        {no: 5, name: "reserved_name", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnumDescriptorProto {
        return new EnumDescriptorProto().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnumDescriptorProto {
        return new EnumDescriptorProto().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnumDescriptorProto {
        return new EnumDescriptorProto().fromJsonString(jsonString, options);
    }

    static equals(a: EnumDescriptorProto | PlainMessage<EnumDescriptorProto> | undefined, b: EnumDescriptorProto | PlainMessage<EnumDescriptorProto> | undefined): boolean {
        return proto2.util.equals(EnumDescriptorProto, a, b);
    }

}

/**
 * @generated from message google.protobuf.EnumDescriptorProto.EnumReservedRange
 */
export class EnumDescriptorProto_EnumReservedRange extends Message<EnumDescriptorProto_EnumReservedRange> {

    /**
     * @generated from field: optional int32 start = 1;
     */
    start?: number;

    /**
     * @generated from field: optional int32 end = 2;
     */
    end?: number;

    constructor(data?: PartialMessage<EnumDescriptorProto_EnumReservedRange>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.EnumDescriptorProto.EnumReservedRange";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "start", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
        {no: 2, name: "end", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnumDescriptorProto_EnumReservedRange {
        return new EnumDescriptorProto_EnumReservedRange().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnumDescriptorProto_EnumReservedRange {
        return new EnumDescriptorProto_EnumReservedRange().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnumDescriptorProto_EnumReservedRange {
        return new EnumDescriptorProto_EnumReservedRange().fromJsonString(jsonString, options);
    }

    static equals(a: EnumDescriptorProto_EnumReservedRange | PlainMessage<EnumDescriptorProto_EnumReservedRange> | undefined, b: EnumDescriptorProto_EnumReservedRange | PlainMessage<EnumDescriptorProto_EnumReservedRange> | undefined): boolean {
        return proto2.util.equals(EnumDescriptorProto_EnumReservedRange, a, b);
    }

}



/**
 * @generated from message google.protobuf.EnumValueDescriptorProto
 */
export class EnumValueDescriptorProto extends Message<EnumValueDescriptorProto> {

    /**
     * @generated from field: optional string name = 1;
     */
    name?: string;

    /**
     * @generated from field: optional int32 number = 2;
     */
    number?: number;

    /**
     * @generated from field: optional google.protobuf.EnumValueOptions options = 3;
     */
    options?: EnumValueOptions;

    constructor(data?: PartialMessage<EnumValueDescriptorProto>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.EnumValueDescriptorProto";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 2, name: "number", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
        {no: 3, name: "options", kind: "message", T: EnumValueOptions, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnumValueDescriptorProto {
        return new EnumValueDescriptorProto().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnumValueDescriptorProto {
        return new EnumValueDescriptorProto().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnumValueDescriptorProto {
        return new EnumValueDescriptorProto().fromJsonString(jsonString, options);
    }

    static equals(a: EnumValueDescriptorProto | PlainMessage<EnumValueDescriptorProto> | undefined, b: EnumValueDescriptorProto | PlainMessage<EnumValueDescriptorProto> | undefined): boolean {
        return proto2.util.equals(EnumValueDescriptorProto, a, b);
    }

}


/**
 * @generated from message google.protobuf.ServiceDescriptorProto
 */
export class ServiceDescriptorProto extends Message<ServiceDescriptorProto> {

    /**
     * @generated from field: optional string name = 1;
     */
    name?: string;

    /**
     * @generated from field: repeated google.protobuf.MethodDescriptorProto method = 2;
     */
    method: MethodDescriptorProto[] = [];

    /**
     * @generated from field: optional google.protobuf.ServiceOptions options = 3;
     */
    options?: ServiceOptions;

    constructor(data?: PartialMessage<ServiceDescriptorProto>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.ServiceDescriptorProto";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 2, name: "method", kind: "message", T: MethodDescriptorProto, repeated: true},
        {no: 3, name: "options", kind: "message", T: ServiceOptions, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceDescriptorProto {
        return new ServiceDescriptorProto().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceDescriptorProto {
        return new ServiceDescriptorProto().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceDescriptorProto {
        return new ServiceDescriptorProto().fromJsonString(jsonString, options);
    }

    static equals(a: ServiceDescriptorProto | PlainMessage<ServiceDescriptorProto> | undefined, b: ServiceDescriptorProto | PlainMessage<ServiceDescriptorProto> | undefined): boolean {
        return proto2.util.equals(ServiceDescriptorProto, a, b);
    }

}


/**
 * @generated from message google.protobuf.MethodDescriptorProto
 */
export class MethodDescriptorProto extends Message<MethodDescriptorProto> {

    /**
     * @generated from field: optional string name = 1;
     */
    name?: string;

    /**
     * @generated from field: optional string input_type = 2;
     */
    inputType?: string;

    /**
     * @generated from field: optional string output_type = 3;
     */
    outputType?: string;

    /**
     * @generated from field: optional google.protobuf.MethodOptions options = 4;
     */
    options?: MethodOptions;

    /**
     * @generated from field: optional bool client_streaming = 5 [default = false];
     */
    clientStreaming?: boolean;

    /**
     * @generated from field: optional bool server_streaming = 6 [default = false];
     */
    serverStreaming?: boolean;

    constructor(data?: PartialMessage<MethodDescriptorProto>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.MethodDescriptorProto";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 2, name: "input_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 3, name: "output_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 4, name: "options", kind: "message", T: MethodOptions, opt: true},
        {no: 5, name: "client_streaming", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 6, name: "server_streaming", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MethodDescriptorProto {
        return new MethodDescriptorProto().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MethodDescriptorProto {
        return new MethodDescriptorProto().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MethodDescriptorProto {
        return new MethodDescriptorProto().fromJsonString(jsonString, options);
    }

    static equals(a: MethodDescriptorProto | PlainMessage<MethodDescriptorProto> | undefined, b: MethodDescriptorProto | PlainMessage<MethodDescriptorProto> | undefined): boolean {
        return proto2.util.equals(MethodDescriptorProto, a, b);
    }

}


/**
 * @generated from message google.protobuf.FileOptions
 */
export class FileOptions extends Message<FileOptions> {

    /**
     * @generated from field: optional string java_package = 1;
     */
    javaPackage?: string;

    /**
     * @generated from field: optional string java_outer_classname = 8;
     */
    javaOuterClassname?: string;

    /**
     * @generated from field: optional bool java_multiple_files = 10 [default = false];
     */
    javaMultipleFiles?: boolean;

    /**
     * @generated from field: optional bool java_generate_equals_and_hash = 20 [deprecated = true];
     * @deprecated
     */
    javaGenerateEqualsAndHash?: boolean;

    /**
     * @generated from field: optional bool java_string_check_utf8 = 27 [default = false];
     */
    javaStringCheckUtf8?: boolean;

    /**
     * @generated from field: optional google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];
     */
    optimizeFor?: FileOptions_OptimizeMode;

    /**
     * @generated from field: optional string go_package = 11;
     */
    goPackage?: string;

    /**
     * @generated from field: optional bool cc_generic_services = 16 [default = false];
     */
    ccGenericServices?: boolean;

    /**
     * @generated from field: optional bool java_generic_services = 17 [default = false];
     */
    javaGenericServices?: boolean;

    /**
     * @generated from field: optional bool py_generic_services = 18 [default = false];
     */
    pyGenericServices?: boolean;

    /**
     * @generated from field: optional bool php_generic_services = 42 [default = false];
     */
    phpGenericServices?: boolean;

    /**
     * @generated from field: optional bool deprecated = 23 [default = false];
     */
    deprecated?: boolean;

    /**
     * @generated from field: optional bool cc_enable_arenas = 31 [default = true];
     */
    ccEnableArenas?: boolean;

    /**
     * @generated from field: optional string objc_class_prefix = 36;
     */
    objcClassPrefix?: string;

    /**
     * @generated from field: optional string csharp_namespace = 37;
     */
    csharpNamespace?: string;

    /**
     * @generated from field: optional string swift_prefix = 39;
     */
    swiftPrefix?: string;

    /**
     * @generated from field: optional string php_class_prefix = 40;
     */
    phpClassPrefix?: string;

    /**
     * @generated from field: optional string php_namespace = 41;
     */
    phpNamespace?: string;

    /**
     * @generated from field: optional string php_metadata_namespace = 44;
     */
    phpMetadataNamespace?: string;

    /**
     * @generated from field: optional string ruby_package = 45;
     */
    rubyPackage?: string;

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<FileOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.FileOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "java_package", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 8, name: "java_outer_classname", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 10, name: "java_multiple_files", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 20, name: "java_generate_equals_and_hash", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true},
        {no: 27, name: "java_string_check_utf8", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 9, name: "optimize_for", kind: "enum", T: proto2.getEnumType(FileOptions_OptimizeMode), opt: true, default: FileOptions_OptimizeMode.SPEED},
        {no: 11, name: "go_package", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 16, name: "cc_generic_services", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 17, name: "java_generic_services", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 18, name: "py_generic_services", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 42, name: "php_generic_services", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 23, name: "deprecated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 31, name: "cc_enable_arenas", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: true},
        {no: 36, name: "objc_class_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 37, name: "csharp_namespace", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 39, name: "swift_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 40, name: "php_class_prefix", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 41, name: "php_namespace", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 44, name: "php_metadata_namespace", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 45, name: "ruby_package", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FileOptions {
        return new FileOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FileOptions {
        return new FileOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FileOptions {
        return new FileOptions().fromJsonString(jsonString, options);
    }

    static equals(a: FileOptions | PlainMessage<FileOptions> | undefined, b: FileOptions | PlainMessage<FileOptions> | undefined): boolean {
        return proto2.util.equals(FileOptions, a, b);
    }

}

/**
 * @generated from enum google.protobuf.FileOptions.OptimizeMode
 */
export enum FileOptions_OptimizeMode {

    /**
     * @generated from enum value: SPEED = 1;
     */
    SPEED = 1,

    /**
     * @generated from enum value: CODE_SIZE = 2;
     */
    CODE_SIZE = 2,

    /**
     * @generated from enum value: LITE_RUNTIME = 3;
     */
    LITE_RUNTIME = 3,

}

// Retrieve enum metadata with: proto2.getEnumType(FileOptions_OptimizeMode)
proto2.util.setEnumType(FileOptions_OptimizeMode, "google.protobuf.FileOptions.OptimizeMode", [
    {no: 1, name: "SPEED"},
    {no: 2, name: "CODE_SIZE"},
    {no: 3, name: "LITE_RUNTIME"},
]);


/**
 * @generated from message google.protobuf.MessageOptions
 */
export class MessageOptions extends Message<MessageOptions> {

    /**
     * @generated from field: optional bool message_set_wire_format = 1 [default = false];
     */
    messageSetWireFormat?: boolean;

    /**
     * @generated from field: optional bool no_standard_descriptor_accessor = 2 [default = false];
     */
    noStandardDescriptorAccessor?: boolean;

    /**
     * @generated from field: optional bool deprecated = 3 [default = false];
     */
    deprecated?: boolean;

    /**
     * @generated from field: optional bool map_entry = 7;
     */
    mapEntry?: boolean;

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<MessageOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.MessageOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "message_set_wire_format", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 2, name: "no_standard_descriptor_accessor", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 3, name: "deprecated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 7, name: "map_entry", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true},
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageOptions {
        return new MessageOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageOptions {
        return new MessageOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageOptions {
        return new MessageOptions().fromJsonString(jsonString, options);
    }

    static equals(a: MessageOptions | PlainMessage<MessageOptions> | undefined, b: MessageOptions | PlainMessage<MessageOptions> | undefined): boolean {
        return proto2.util.equals(MessageOptions, a, b);
    }

}


/**
 * @generated from message google.protobuf.FieldOptions
 */
export class FieldOptions extends Message<FieldOptions> {

    /**
     * @generated from field: optional google.protobuf.FieldOptions.CType ctype = 1 [default = STRING];
     */
    ctype?: FieldOptions_CType;

    /**
     * @generated from field: optional bool packed = 2;
     */
    packed?: boolean;

    /**
     * @generated from field: optional google.protobuf.FieldOptions.JSType jstype = 6 [default = JS_NORMAL];
     */
    jstype?: FieldOptions_JSType;

    /**
     * @generated from field: optional bool lazy = 5 [default = false];
     */
    lazy?: boolean;

    /**
     * @generated from field: optional bool deprecated = 3 [default = false];
     */
    deprecated?: boolean;

    /**
     * @generated from field: optional bool weak = 10 [default = false];
     */
    weak?: boolean;

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<FieldOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.FieldOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "ctype", kind: "enum", T: proto2.getEnumType(FieldOptions_CType), opt: true, default: FieldOptions_CType.STRING},
        {no: 2, name: "packed", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true},
        {no: 6, name: "jstype", kind: "enum", T: proto2.getEnumType(FieldOptions_JSType), opt: true, default: FieldOptions_JSType.JS_NORMAL},
        {no: 5, name: "lazy", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 3, name: "deprecated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 10, name: "weak", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FieldOptions {
        return new FieldOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FieldOptions {
        return new FieldOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FieldOptions {
        return new FieldOptions().fromJsonString(jsonString, options);
    }

    static equals(a: FieldOptions | PlainMessage<FieldOptions> | undefined, b: FieldOptions | PlainMessage<FieldOptions> | undefined): boolean {
        return proto2.util.equals(FieldOptions, a, b);
    }

}

/**
 * @generated from enum google.protobuf.FieldOptions.CType
 */
export enum FieldOptions_CType {

    /**
     * @generated from enum value: STRING = 0;
     */
    STRING = 0,

    /**
     * @generated from enum value: CORD = 1;
     */
    CORD = 1,

    /**
     * @generated from enum value: STRING_PIECE = 2;
     */
    STRING_PIECE = 2,

}

// Retrieve enum metadata with: proto2.getEnumType(FieldOptions_CType)
proto2.util.setEnumType(FieldOptions_CType, "google.protobuf.FieldOptions.CType", [
    {no: 0, name: "STRING"},
    {no: 1, name: "CORD"},
    {no: 2, name: "STRING_PIECE"},
]);

/**
 * @generated from enum google.protobuf.FieldOptions.JSType
 */
export enum FieldOptions_JSType {

    /**
     * @generated from enum value: JS_NORMAL = 0;
     */
    JS_NORMAL = 0,

    /**
     * @generated from enum value: JS_STRING = 1;
     */
    JS_STRING = 1,

    /**
     * @generated from enum value: JS_NUMBER = 2;
     */
    JS_NUMBER = 2,

}

// Retrieve enum metadata with: proto2.getEnumType(FieldOptions_JSType)
proto2.util.setEnumType(FieldOptions_JSType, "google.protobuf.FieldOptions.JSType", [
    {no: 0, name: "JS_NORMAL"},
    {no: 1, name: "JS_STRING"},
    {no: 2, name: "JS_NUMBER"},
]);


/**
 * @generated from message google.protobuf.OneofOptions
 */
export class OneofOptions extends Message<OneofOptions> {

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<OneofOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.OneofOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OneofOptions {
        return new OneofOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OneofOptions {
        return new OneofOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OneofOptions {
        return new OneofOptions().fromJsonString(jsonString, options);
    }

    static equals(a: OneofOptions | PlainMessage<OneofOptions> | undefined, b: OneofOptions | PlainMessage<OneofOptions> | undefined): boolean {
        return proto2.util.equals(OneofOptions, a, b);
    }

}


/**
 * @generated from message google.protobuf.EnumOptions
 */
export class EnumOptions extends Message<EnumOptions> {

    /**
     * @generated from field: optional bool allow_alias = 2;
     */
    allowAlias?: boolean;

    /**
     * @generated from field: optional bool deprecated = 3 [default = false];
     */
    deprecated?: boolean;

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<EnumOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.EnumOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 2, name: "allow_alias", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true},
        {no: 3, name: "deprecated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnumOptions {
        return new EnumOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnumOptions {
        return new EnumOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnumOptions {
        return new EnumOptions().fromJsonString(jsonString, options);
    }

    static equals(a: EnumOptions | PlainMessage<EnumOptions> | undefined, b: EnumOptions | PlainMessage<EnumOptions> | undefined): boolean {
        return proto2.util.equals(EnumOptions, a, b);
    }

}


/**
 * @generated from message google.protobuf.EnumValueOptions
 */
export class EnumValueOptions extends Message<EnumValueOptions> {

    /**
     * @generated from field: optional bool deprecated = 1 [default = false];
     */
    deprecated?: boolean;

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<EnumValueOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.EnumValueOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "deprecated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): EnumValueOptions {
        return new EnumValueOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): EnumValueOptions {
        return new EnumValueOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): EnumValueOptions {
        return new EnumValueOptions().fromJsonString(jsonString, options);
    }

    static equals(a: EnumValueOptions | PlainMessage<EnumValueOptions> | undefined, b: EnumValueOptions | PlainMessage<EnumValueOptions> | undefined): boolean {
        return proto2.util.equals(EnumValueOptions, a, b);
    }

}


/**
 * @generated from message google.protobuf.ServiceOptions
 */
export class ServiceOptions extends Message<ServiceOptions> {

    /**
     * @generated from field: optional bool deprecated = 33 [default = false];
     */
    deprecated?: boolean;

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<ServiceOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.ServiceOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 33, name: "deprecated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ServiceOptions {
        return new ServiceOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ServiceOptions {
        return new ServiceOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ServiceOptions {
        return new ServiceOptions().fromJsonString(jsonString, options);
    }

    static equals(a: ServiceOptions | PlainMessage<ServiceOptions> | undefined, b: ServiceOptions | PlainMessage<ServiceOptions> | undefined): boolean {
        return proto2.util.equals(ServiceOptions, a, b);
    }

}


/**
 * @generated from message google.protobuf.MethodOptions
 */
export class MethodOptions extends Message<MethodOptions> {

    /**
     * @generated from field: optional bool deprecated = 33 [default = false];
     */
    deprecated?: boolean;

    /**
     * @generated from field: optional google.protobuf.MethodOptions.IdempotencyLevel idempotency_level = 34 [default = IDEMPOTENCY_UNKNOWN];
     */
    idempotencyLevel?: MethodOptions_IdempotencyLevel;

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption uninterpreted_option = 999;
     */
    uninterpretedOption: UninterpretedOption[] = [];

    constructor(data?: PartialMessage<MethodOptions>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.MethodOptions";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 33, name: "deprecated", kind: "scalar", T: 8 /* ScalarType.BOOL */, opt: true, default: false},
        {no: 34, name: "idempotency_level", kind: "enum", T: proto2.getEnumType(MethodOptions_IdempotencyLevel), opt: true, default: MethodOptions_IdempotencyLevel.IDEMPOTENCY_UNKNOWN},
        {no: 999, name: "uninterpreted_option", kind: "message", T: UninterpretedOption, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MethodOptions {
        return new MethodOptions().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MethodOptions {
        return new MethodOptions().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MethodOptions {
        return new MethodOptions().fromJsonString(jsonString, options);
    }

    static equals(a: MethodOptions | PlainMessage<MethodOptions> | undefined, b: MethodOptions | PlainMessage<MethodOptions> | undefined): boolean {
        return proto2.util.equals(MethodOptions, a, b);
    }

}

/**
 * @generated from enum google.protobuf.MethodOptions.IdempotencyLevel
 */
export enum MethodOptions_IdempotencyLevel {

    /**
     * @generated from enum value: IDEMPOTENCY_UNKNOWN = 0;
     */
    IDEMPOTENCY_UNKNOWN = 0,

    /**
     * @generated from enum value: NO_SIDE_EFFECTS = 1;
     */
    NO_SIDE_EFFECTS = 1,

    /**
     * @generated from enum value: IDEMPOTENT = 2;
     */
    IDEMPOTENT = 2,

}

// Retrieve enum metadata with: proto2.getEnumType(MethodOptions_IdempotencyLevel)
proto2.util.setEnumType(MethodOptions_IdempotencyLevel, "google.protobuf.MethodOptions.IdempotencyLevel", [
    {no: 0, name: "IDEMPOTENCY_UNKNOWN"},
    {no: 1, name: "NO_SIDE_EFFECTS"},
    {no: 2, name: "IDEMPOTENT"},
]);


/**
 * @generated from message google.protobuf.UninterpretedOption
 */
export class UninterpretedOption extends Message<UninterpretedOption> {

    /**
     * @generated from field: repeated google.protobuf.UninterpretedOption.NamePart name = 2;
     */
    name: UninterpretedOption_NamePart[] = [];

    /**
     * @generated from field: optional string identifier_value = 3;
     */
    identifierValue?: string;

    /**
     * @generated from field: optional uint64 positive_int_value = 4;
     */
    positiveIntValue?: bigint;

    /**
     * @generated from field: optional int64 negative_int_value = 5;
     */
    negativeIntValue?: bigint;

    /**
     * @generated from field: optional double double_value = 6;
     */
    doubleValue?: number;

    /**
     * @generated from field: optional bytes string_value = 7;
     */
    stringValue?: Uint8Array;

    /**
     * @generated from field: optional string aggregate_value = 8;
     */
    aggregateValue?: string;

    constructor(data?: PartialMessage<UninterpretedOption>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.UninterpretedOption";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 2, name: "name", kind: "message", T: UninterpretedOption_NamePart, repeated: true},
        {no: 3, name: "identifier_value", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 4, name: "positive_int_value", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true},
        {no: 5, name: "negative_int_value", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true},
        {no: 6, name: "double_value", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, opt: true},
        {no: 7, name: "string_value", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true},
        {no: 8, name: "aggregate_value", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UninterpretedOption {
        return new UninterpretedOption().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UninterpretedOption {
        return new UninterpretedOption().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UninterpretedOption {
        return new UninterpretedOption().fromJsonString(jsonString, options);
    }

    static equals(a: UninterpretedOption | PlainMessage<UninterpretedOption> | undefined, b: UninterpretedOption | PlainMessage<UninterpretedOption> | undefined): boolean {
        return proto2.util.equals(UninterpretedOption, a, b);
    }

}

/**
 * @generated from message google.protobuf.UninterpretedOption.NamePart
 */
export class UninterpretedOption_NamePart extends Message<UninterpretedOption_NamePart> {

    /**
     * @generated from field: required string name_part = 1;
     */
    namePart?: string;

    /**
     * @generated from field: required bool is_extension = 2;
     */
    isExtension?: boolean;

    constructor(data?: PartialMessage<UninterpretedOption_NamePart>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.UninterpretedOption.NamePart";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "name_part", kind: "scalar", T: 9 /* ScalarType.STRING */},
        {no: 2, name: "is_extension", kind: "scalar", T: 8 /* ScalarType.BOOL */},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UninterpretedOption_NamePart {
        return new UninterpretedOption_NamePart().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UninterpretedOption_NamePart {
        return new UninterpretedOption_NamePart().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UninterpretedOption_NamePart {
        return new UninterpretedOption_NamePart().fromJsonString(jsonString, options);
    }

    static equals(a: UninterpretedOption_NamePart | PlainMessage<UninterpretedOption_NamePart> | undefined, b: UninterpretedOption_NamePart | PlainMessage<UninterpretedOption_NamePart> | undefined): boolean {
        return proto2.util.equals(UninterpretedOption_NamePart, a, b);
    }

}



/**
 * @generated from message google.protobuf.SourceCodeInfo
 */
export class SourceCodeInfo extends Message<SourceCodeInfo> {

    /**
     * @generated from field: repeated google.protobuf.SourceCodeInfo.Location location = 1;
     */
    location: SourceCodeInfo_Location[] = [];

    constructor(data?: PartialMessage<SourceCodeInfo>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.SourceCodeInfo";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "location", kind: "message", T: SourceCodeInfo_Location, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SourceCodeInfo {
        return new SourceCodeInfo().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SourceCodeInfo {
        return new SourceCodeInfo().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SourceCodeInfo {
        return new SourceCodeInfo().fromJsonString(jsonString, options);
    }

    static equals(a: SourceCodeInfo | PlainMessage<SourceCodeInfo> | undefined, b: SourceCodeInfo | PlainMessage<SourceCodeInfo> | undefined): boolean {
        return proto2.util.equals(SourceCodeInfo, a, b);
    }

}

/**
 * @generated from message google.protobuf.SourceCodeInfo.Location
 */
export class SourceCodeInfo_Location extends Message<SourceCodeInfo_Location> {

    /**
     * @generated from field: repeated int32 path = 1 [packed = true];
     */
    path: number[] = [];

    /**
     * @generated from field: repeated int32 span = 2 [packed = true];
     */
    span: number[] = [];

    /**
     * @generated from field: optional string leading_comments = 3;
     */
    leadingComments?: string;

    /**
     * @generated from field: optional string trailing_comments = 4;
     */
    trailingComments?: string;

    /**
     * @generated from field: repeated string leading_detached_comments = 6;
     */
    leadingDetachedComments: string[] = [];

    constructor(data?: PartialMessage<SourceCodeInfo_Location>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.SourceCodeInfo.Location";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "path", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true, packed: true},
        {no: 2, name: "span", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true, packed: true},
        {no: 3, name: "leading_comments", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 4, name: "trailing_comments", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 6, name: "leading_detached_comments", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): SourceCodeInfo_Location {
        return new SourceCodeInfo_Location().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): SourceCodeInfo_Location {
        return new SourceCodeInfo_Location().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): SourceCodeInfo_Location {
        return new SourceCodeInfo_Location().fromJsonString(jsonString, options);
    }

    static equals(a: SourceCodeInfo_Location | PlainMessage<SourceCodeInfo_Location> | undefined, b: SourceCodeInfo_Location | PlainMessage<SourceCodeInfo_Location> | undefined): boolean {
        return proto2.util.equals(SourceCodeInfo_Location, a, b);
    }

}



/**
 * @generated from message google.protobuf.GeneratedCodeInfo
 */
export class GeneratedCodeInfo extends Message<GeneratedCodeInfo> {

    /**
     * @generated from field: repeated google.protobuf.GeneratedCodeInfo.Annotation annotation = 1;
     */
    annotation: GeneratedCodeInfo_Annotation[] = [];

    constructor(data?: PartialMessage<GeneratedCodeInfo>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.GeneratedCodeInfo";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "annotation", kind: "message", T: GeneratedCodeInfo_Annotation, repeated: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeneratedCodeInfo {
        return new GeneratedCodeInfo().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeneratedCodeInfo {
        return new GeneratedCodeInfo().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeneratedCodeInfo {
        return new GeneratedCodeInfo().fromJsonString(jsonString, options);
    }

    static equals(a: GeneratedCodeInfo | PlainMessage<GeneratedCodeInfo> | undefined, b: GeneratedCodeInfo | PlainMessage<GeneratedCodeInfo> | undefined): boolean {
        return proto2.util.equals(GeneratedCodeInfo, a, b);
    }

}

/**
 * @generated from message google.protobuf.GeneratedCodeInfo.Annotation
 */
export class GeneratedCodeInfo_Annotation extends Message<GeneratedCodeInfo_Annotation> {

    /**
     * @generated from field: repeated int32 path = 1 [packed = true];
     */
    path: number[] = [];

    /**
     * @generated from field: optional string source_file = 2;
     */
    sourceFile?: string;

    /**
     * @generated from field: optional int32 begin = 3;
     */
    begin?: number;

    /**
     * @generated from field: optional int32 end = 4;
     */
    end?: number;

    constructor(data?: PartialMessage<GeneratedCodeInfo_Annotation>) {
        super();
        proto2.util.initPartial(data, this);
    }

    static readonly runtime = proto2;
    static readonly typeName = "google.protobuf.GeneratedCodeInfo.Annotation";
    static readonly fields: FieldList = proto2.util.newFieldList(() => [
        {no: 1, name: "path", kind: "scalar", T: 5 /* ScalarType.INT32 */, repeated: true, packed: true},
        {no: 2, name: "source_file", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true},
        {no: 3, name: "begin", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
        {no: 4, name: "end", kind: "scalar", T: 5 /* ScalarType.INT32 */, opt: true},
    ]);

    static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GeneratedCodeInfo_Annotation {
        return new GeneratedCodeInfo_Annotation().fromBinary(bytes, options);
    }

    static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GeneratedCodeInfo_Annotation {
        return new GeneratedCodeInfo_Annotation().fromJson(jsonValue, options);
    }

    static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GeneratedCodeInfo_Annotation {
        return new GeneratedCodeInfo_Annotation().fromJsonString(jsonString, options);
    }

    static equals(a: GeneratedCodeInfo_Annotation | PlainMessage<GeneratedCodeInfo_Annotation> | undefined, b: GeneratedCodeInfo_Annotation | PlainMessage<GeneratedCodeInfo_Annotation> | undefined): boolean {
        return proto2.util.equals(GeneratedCodeInfo_Annotation, a, b);
    }

}



